// Unlimited-only prompts (never used as dailies)

// "Patrick" -> "Saint Patrick~St Patrick~Patrick"; a leading "!" keeps the entry as written
const saints = s => s.split('|').map(it => {
  if (/\?\s+$/.test(it) || /\sdup\s*$/.test(it)) return it;
  const raw = it.trim();
  if (raw[0] === '!') return raw.slice(1);
  return raw.split('~').map(x => x.trim()).flatMap((x, i) => i ? [x, 'Saint ' + x, 'St ' + x] : ['Saint ' + x, 'St ' + x, x]).join('~');
}).join('|');

pool([
{q:"Name a city or town in Canada", r:"A city, town or village in Canada.",
p:"Toronto|Vancouver|Montreal~Montréal|Ottawa|Calgary|Quebec City~Québec~Quebec|Edmonton|Winnipeg",
c:"Paris~Paris, Ontario",
s:"Halifax|Victoria|Regina|Saskatoon|St. John's~St Johns|Fredericton|Charlottetown|Whitehorse|Yellowknife|Iqaluit|Hamilton|London~London, Ontario|Kitchener|Waterloo|Windsor|Mississauga|Brampton|Markham|Vaughan|Oakville|Burlington|Niagara Falls|St. Catharines|Guelph|Barrie|Kingston|Oshawa|Sudbury~Greater Sudbury|Thunder Bay|Sault Ste. Marie|North Bay|Timmins|Peterborough|Belleville|Cornwall|Gatineau|Laval|Longueuil|Sherbrooke|Trois-Rivières|Saguenay|Lévis|Terrebonne|Surrey|Burnaby|Richmond|Coquitlam|Abbotsford|Kelowna|Kamloops|Nanaimo|Prince George|Whistler|Banff|Jasper|Canmore|Red Deer|Lethbridge|Medicine Hat|Grande Prairie|Fort McMurray|Moose Jaw|Prince Albert|Brandon|Churchill|Moncton|Saint John|Sydney~Sydney, Nova Scotia|Dartmouth|Truro|Corner Brook|Gander|Tofino|Dawson City|Inuvik|Tuktoyaktuk|Niagara-on-the-Lake|Stratford|Kenora|Mont-Tremblant|Squamish|Lunenburg|Peggy's Cove",
a:"Rimouski|Gaspé|Chicoutimi|Rouyn-Noranda|Val-d'Or|Baie-Comeau|Sept-Îles|Drummondville|Granby|Saint-Jérôme|Joliette|Victoriaville|Magog|Salaberry-de-Valleyfield|Chibougamau|Tadoussac|Baie-Saint-Paul|Penticton|Vernon|Nelson|Revelstoke|Cranbrook|Fernie|Prince Rupert|Powell River|Courtenay|Campbell River|Duncan|Chilliwack|Langley|Maple Ridge|Port Moody|New Westminster|North Vancouver|West Vancouver|Airdrie|Okotoks|Cochrane|Lloydminster|Camrose|Wetaskiwin|Drumheller|Swift Current|North Battleford|Yorkton|Estevan|Weyburn|Flin Flon|The Pas|Thompson|Steinbach|Portage la Prairie|Selkirk|Dauphin|Owen Sound|Collingwood|Orillia|Huntsville|Cobourg|Brockville|Pembroke|Sarnia|Chatham|Leamington|Woodstock|Brantford|Cambridge|Welland|Orangeville|Midland|Elliot Lake|Kapuskasing|Kirkland Lake|Moosonee|Attawapiskat|Bathurst|Edmundston|Miramichi|Campbellton|Summerside|Antigonish|Yarmouth|Wolfville|Annapolis Royal|Baddeck|Glace Bay|New Glasgow|Grand Falls-Windsor|Labrador City|Happy Valley-Goose Bay|Twillingate|Bonavista|Rankin Inlet|Cambridge Bay|Pond Inlet|Hay River|Fort Smith|Watson Lake|Carcross|Kuujjuaq|Chisasibi|Stephenville|Haines Junction|Whitby|Ajax|Pickering|Richmond Hill|Newmarket|Aurora|Milton|St. Albert|Sherwood Park|Spruce Grove|Fort St. John|Dawson Creek|Williams Lake|Quesnel|Smithers|Terrace|Kitimat|Port Hardy|Salt Spring Island|Sooke|Harrison Hot Springs|Osoyoos|Golden|Invermere|Kimberley|Pincher Creek|Waterton|Lake Louise|Hinton|Whitecourt|Peace River|High Level|La Ronge|Meadow Lake|Gimli|Morden|Winkler",
d:"Grise Fiord|Resolute~Resolute Bay|Arviat|Baker Lake|Kugluktuk|Igloolik|Sachs Harbour|Aklavik|Old Crow|Paulatuk|Ulukhaktok|Kimmirut|Pangnirtung|Qikiqtarjuaq|Clyde River|Arctic Bay|Gjoa Haven|Taloyoak|Kugaaruk|Naujaat~Repulse Bay|Coral Harbour|Chesterfield Inlet|Whale Cove|Sanikiluaq|Nain|Hopedale|Makkovik|Rigolet|Cartwright|Red Bay|L'Anse aux Meadows|Fogo|Ferryland|Trepassey|Placentia|Channel-Port aux Basques~Port aux Basques|Uranium City|Stewart|Atlin|Telegraph Creek|Bella Coola|Alert Bay|Sointula|Ucluelet|Masset|Daajing Giids~Queen Charlotte|Moose Factory|Fort Albany|Pikangikum|Wawa|Sioux Lookout|Dryden|Fort Frances|Atikokan|Marathon|Nipigon|Hearst|Chapleau|Temiskaming Shores|Mattawa|Blind River|Espanola|Gore Bay|Manitouwadge|Schefferville|Fermont|Havre-Saint-Pierre|Natashquan|Blanc-Sablon|Kuujjuarapik|Inukjuak|Puvirnituq|Ivujivik|Kangiqsujuaq|Salluit|Gillam|Lynn Lake|Norman Wells|Tulita|Fort Simpson|Fort Providence|Behchokǫ̀~Behchoko|Tsiigehtchic|Fort McPherson|Mayo|Faro|Ross River|Beaver Creek|Burwash Landing",
k:"Alert|The northernmost permanently inhabited place on Earth — a military station in Nunavut about 800 km from the North Pole."},

{q:"Name a city in Africa", r:"A city or town anywhere in Africa.",
p:"Cairo|Lagos|Nairobi|Cape Town|Johannesburg~Joburg|Marrakesh~Marrakech|Casablanca|Addis Ababa",
c:"Ceuta|Melilla",
s:"Alexandria|Giza|Luxor|Aswan|Sharm El Sheikh|Hurghada|Port Said|Suez|Tunis|Carthage|Sousse|Sfax|Algiers|Oran|Constantine|Tripoli|Benghazi|Rabat|Fez~Fes|Tangier|Agadir|Essaouira|Chefchaouen|Meknes|Ouarzazate|Khartoum|Omdurman|Port Sudan|Juba|Asmara|Djibouti~Djibouti City|Mogadishu|Hargeisa|Kampala|Kigali|Bujumbura|Dar es Salaam|Dodoma|Zanzibar~Zanzibar City~Stone Town|Arusha|Mombasa|Kisumu|Nakuru|Lusaka|Livingstone|Harare|Bulawayo|Victoria Falls|Lilongwe|Blantyre|Maputo|Beira|Gaborone|Windhoek|Swakopmund|Walvis Bay|Maseru|Mbabane|Durban|Pretoria|Port Elizabeth~Gqeberha|Bloemfontein|Soweto|Stellenbosch|Pietermaritzburg|East London|Kimberley|Antananarivo|Port Louis|Victoria~Victoria, Seychelles|Moroni|Luanda|Kinshasa|Lubumbashi|Goma|Brazzaville|Pointe-Noire|Libreville|Yaoundé~Yaounde|Douala|Malabo|Bangui|N'Djamena|Niamey|Bamako|Timbuktu~Tombouctou|Djenné~Djenne|Ouagadougou|Abidjan|Yamoussoukro|Accra|Kumasi|Lomé~Lome|Cotonou|Porto-Novo|Abuja|Kano|Ibadan|Port Harcourt|Benin City|Enugu|Kaduna|Dakar|Saint-Louis|Touba|Banjul|Bissau|Conakry|Freetown|Monrovia|Nouakchott|Praia|São Tomé~Sao Tome|Dire Dawa|Gondar|Lalibela|Bahir Dar|Mekelle|Axum~Aksum|Harar|Las Palmas|Santa Cruz de Tenerife",
a:"Ghardaïa~Ghardaia|Tamanrasset|Timimoun|Béchar|Annaba|Tlemcen|Ghat|Sabha|Misrata|Tobruk|Derna|Kairouan|Tozeur|Djerba~Houmt Souk|Bizerte|Monastir|Hammamet|Nabeul|Gabès|Siwa|Asyut|Minya|Tanta|Mansoura|Zagazig|Ismailia|Faiyum|Qena|Sohag|Edfu|Kom Ombo|Abu Simbel|El Alamein|Marsa Matruh|Dahab|Marsa Alam|Wadi Halfa|Atbara|Kassala|El Obeid|Nyala|Kosti|Wad Madani|Massawa|Keren|Berbera|Bosaso|Kismayo|Baidoa|Jijiga|Hawassa|Jimma|Arba Minch|Adama|Entebbe|Jinja|Gulu|Mbarara|Fort Portal|Musanze|Huye~Butare|Rubavu~Gisenyi|Mwanza|Moshi|Tanga|Mbeya|Morogoro|Bagamoyo|Kilwa|Lamu|Malindi|Eldoret|Nanyuki|Naivasha|Thika|Ndola|Kitwe|Kabwe|Mutare|Gweru|Masvingo|Kariba|Zomba|Mzuzu|Nampula|Quelimane|Tete|Pemba|Inhambane|Ilha de Moçambique~Island of Mozambique|Francistown|Maun|Kasane|Lüderitz~Luderitz|Oshakati|Rundu|Keetmanshoop|Tsumeb|Polokwane|Mbombela~Nelspruit|Rustenburg|George|Knysna|Oudtshoorn|Hermanus|Paarl|Franschhoek|Upington|Mahikeng~Mafikeng|Mthatha|Richards Bay|Ladysmith|Toamasina|Fianarantsoa|Toliara|Mahajanga|Curepipe|Saint-Denis~Saint-Denis, Réunion|Mamoudzou|Huambo|Lobito|Benguela|Lubango|Kisangani|Kananga|Mbuji-Mayi|Bukavu|Kolwezi|Matadi|Franceville|Port-Gentil|Bata|Garoua|Bamenda|Maroua|Kribi|Buea|Sarh|Abéché|Agadez|Zinder|Maradi|Gao|Mopti|Ségou|Kayes|Bobo-Dioulasso|Bouaké|San-Pédro|Grand-Bassam|Korhogo|Tamale|Cape Coast|Elmina|Takoradi|Tema|Kpalimé|Parakou|Ouidah|Abomey|Zaria|Jos|Maiduguri|Sokoto|Calabar|Onitsha|Aba|Owerri|Warri|Uyo|Ilorin|Osogbo~Oshogbo|Abeokuta|Ile-Ife~Ife|Ziguinchor|Thiès|Kaolack|Nouadhibou|Chinguetti|Ouadane|Atar|Kankan|Bo|Kenema|Buchanan|Mindelo|Laayoune|Dakhla|Tétouan~Tetouan|Oujda|Nador",
d:"Oualata|Tichitt|Kidal|Tessalit|Bilma|Faya-Largeau|Kufra|Ghadames|Ubari|Murzuq|Awjila|Zliten|Djanet|In Salah|Tindouf|Illizi|Béni Abbès|Taghit|El Oued|Touggourt|Ouargla|Laghouat|Bou Saâda|Figuig|Merzouga|Zagora|Tinghir|Erfoud|Rissani|Midelt|Azrou|Moulay Idriss|Asilah|Larache|Al Hoceima|Tarfaya|Sidi Ifni|Tataouine|Matmata|Douz|Nefta|Kebili|Dongola|Karima|Shendi|Suakin|Nakfa|Adigrat|Debre Markos|Gambela|Jinka|Konso|Moyale|Marsabit|Lodwar|Garissa|Wajir|Mandera|Kakuma|Arua|Moroto|Kabale|Kigoma|Ujiji|Tabora|Songea|Lindi|Mtwara|Sumbawanga|Mpika|Kasama|Mongu|Chipata|Solwezi|Nkhata Bay|Karonga|Lichinga|Vilankulo|Xai-Xai|Ghanzi|Tsabong|Opuwo|Katima Mulilo|Kolmanskop|Springbok|Sutherland|Graaff-Reinet|Nieu-Bethesda|Barberton|Pilgrim's Rest|Musina|Thohoyandou|Phalaborwa|Semonkong|Mokhotlong|Manzini|Lobamba|Morondava|Antsiranana~Diego Suarez|Tôlagnaro~Fort Dauphin|Maroantsetra|Mahébourg|Kindu|Isiro|Bunia|Mbandaka|Gemena|Ouesso|Impfondo|Makokou|Oyem|Lambaréné|Ebolowa|Bertoua|Ngaoundéré|Birao|Bangassou|Diffa|Tahoua|Arlit|Araouane|Taoudenni|Kita|Kédougou|Podor|Matam|Rosso|Kiffa|Néma|Boké|Labé|Nzérékoré|Makeni|Harper|Zwedru|Man|Odienné|Bolgatanga|Wa|Navrongo|Dapaong|Natitingou|Kandi|Djougou|Kousséri",
k:"Ifrane|A Moroccan mountain town of Alpine-style chalets, nicknamed 'the Switzerland of Morocco' — it holds Africa's record low of −23.9 °C."},

{q:"Name an aircraft", r:"A plane, helicopter, airship or other aircraft — a model, type or famous individual aircraft.",
p:"Boeing 747~747~Jumbo Jet~Jumbo jet|Concorde|Spitfire~Supermarine Spitfire|Airbus A380~A380|Boeing 737~737|Wright Flyer|Cessna~Cessna 172|Black Hawk~UH-60 Black Hawk~Blackhawk",
c:"Air Force One",
s:"Boeing 707~707|Boeing 727~727|Boeing 757~757|Boeing 767~767|Boeing 777~777~Triple Seven|Boeing 787~787~Dreamliner~787 Dreamliner|Boeing 737 MAX~737 MAX|Airbus A320~A320|Airbus A319~A319|Airbus A321~A321|Airbus A330~A330|Airbus A340~A340|Airbus A350~A350|Airbus A300~A300|Airbus A220~A220|DC-10~McDonnell Douglas DC-10|MD-11~McDonnell Douglas MD-11|MD-80|DC-3~Douglas DC-3|C-47~Dakota~Skytrain|L-1011 TriStar~TriStar~Lockheed TriStar|Constellation~Lockheed Constellation~Connie|Tu-144~Tupolev Tu-144~Concordski|Embraer E-Jet~Embraer E190~Embraer|CRJ~Bombardier CRJ~Canadair Regional Jet|ATR 72~ATR|Dash 8~Q400~Bombardier Dash 8|Fokker 100|BAe 146~Avro RJ|de Havilland Comet~Comet|Vickers Viscount~Viscount|F-16~F-16 Fighting Falcon~Fighting Falcon|F-15~F-15 Eagle|F-22~F-22 Raptor~Raptor|F-35~F-35 Lightning II|F-14~F-14 Tomcat~Tomcat|F/A-18 Hornet~F-18~Hornet~Super Hornet|F-4 Phantom~F-4~Phantom|F-117 Nighthawk~F-117~Stealth fighter|B-2 Spirit~B-2~Stealth bomber|B-52~B-52 Stratofortress|B-17~Flying Fortress~B-17 Flying Fortress|B-29~B-29 Superfortress|Enola Gay|SR-71~SR-71 Blackbird~Blackbird|U-2|A-10~A-10 Warthog~Warthog~Thunderbolt II|C-130~C-130 Hercules~Hercules|C-17~C-17 Globemaster|C-5 Galaxy~C-5|AC-130~AC-130 Gunship|P-51 Mustang~P-51~Mustang|P-38 Lightning~P-38|P-47 Thunderbolt~P-47|F4U Corsair~Corsair|F6F Hellcat~Hellcat|Hurricane~Hawker Hurricane|Lancaster~Avro Lancaster|Mosquito~de Havilland Mosquito|Bf 109~Messerschmitt Bf 109~Me 109|Me 262~Messerschmitt Me 262|Fw 190~Focke-Wulf Fw 190|Stuka~Ju 87|Ju 52~Junkers Ju 52|Zero~Mitsubishi Zero~A6M Zero|Sopwith Camel|Fokker Dr.I~Fokker Triplane~Red Baron's triplane|Harrier~Harrier Jump Jet|Eurofighter Typhoon~Typhoon~Eurofighter|Tornado~Panavia Tornado|Rafale~Dassault Rafale|Mirage~Mirage 2000~Dassault Mirage|Gripen~Saab Gripen|Viggen~Saab Viggen|Draken~Saab Draken|MiG-15|MiG-21|MiG-29|MiG-31|Su-27~Sukhoi Su-27|Su-57~Sukhoi Su-57|Tu-95~Tu-95 Bear|Tu-160~Blackjack|Vulcan~Avro Vulcan|Hawk~BAE Hawk|Chinook~CH-47 Chinook|Apache~AH-64 Apache|Huey~UH-1~UH-1 Iroquois|Sea King|Osprey~V-22 Osprey|Westland Lynx~Lynx|Robinson R22~R22|JetRanger~Bell 206|Piper Cub~J-3 Cub|Piper~Piper PA-28~Cherokee|Beechcraft King Air~King Air|Learjet|Gulfstream~Gulfstream G650|Cirrus SR22|Pilatus PC-12|Twin Otter~DHC-6 Twin Otter|de Havilland Beaver~Beaver~DHC-2|An-225~Antonov An-225~Mriya|An-124~Antonov An-124~Ruslan|Beluga~Airbus Beluga|Dreamlifter|Spruce Goose~Hughes H-4 Hercules|Hindenburg|Graf Zeppelin|Zeppelin|Goodyear Blimp~Blimp|Spirit of St. Louis|Bell X-1|X-15~North American X-15|Space Shuttle|SpaceShipOne|Solar Impulse|Blériot XI~Bleriot XI|Global Hawk|Predator~MQ-1 Predator|Reaper~MQ-9 Reaper|Bayraktar TB2|Chengdu J-20~J-20|Tejas~HAL Tejas|Sikorsky S-92|Mi-8~Mil Mi-8|Mi-24~Hind",
a:"Lockheed Electra~Electra|Ford Trimotor~Tin Goose|Boeing 314 Clipper~Clipper|Short Sunderland~Sunderland|PBY Catalina~Catalina|Supermarine S.6B|Gee Bee|Curtiss JN-4~Jenny|Vickers Vimy|Fokker Eindecker|SPAD S.XIII|Nieuport 17|Albatros D.III|Sopwith Pup|Bristol F.2 Fighter|Gotha G.V~Gotha|Handley Page O/400|Ilya Muromets~Sikorsky Ilya Muromets|Me 163 Komet~Komet|Horten Ho 229|Arado Ar 234|Heinkel He 111|Heinkel He 178|Dornier Do 335|Fairey Swordfish~Swordfish~Stringbag|Gloster Meteor~Meteor|de Havilland Vampire|Hawker Hunter|English Electric Lightning|BAC TSR-2~TSR-2|Avro Arrow|Vickers VC10~VC10|Hawker Siddeley Trident~Trident|BAC One-Eleven|Bristol Britannia|Bristol Brabazon|Saunders-Roe Princess|Avro Shackleton|Handley Page Victor~Victor|Nimrod~Hawker Siddeley Nimrod|B-58 Hustler|Convair B-36~B-36 Peacemaker|XB-70 Valkyrie~Valkyrie|B-1 Lancer~B-1|F-104 Starfighter|F-86 Sabre|F-100 Super Sabre|F-111~Aardvark|F-5~F-5 Tiger|A-4 Skyhawk|A-6 Intruder|E-3 Sentry~AWACS|KC-135~Stratotanker|P-3 Orion|Boeing E-4~Doomsday plane|YF-23|X-29|X-43|Tu-22|Tu-134|Tu-154|Tu-204|Il-62|Il-76|Il-86|Yak-40|Yak-42|An-2~Antonov An-2|An-12|An-22|Be-200|Mi-26~Mil Mi-26|Ka-50~Black Shark|Ka-52~Alligator|Sukhoi Superjet~Superjet 100|Comac C919~C919|MC-21~Irkutsk MC-21|Kawasaki P-1|ShinMaywa US-2|JF-17~JF-17 Thunder|KAI T-50|Dassault Falcon~Falcon 7X|Super Étendard|Caravelle~Sud Aviation Caravelle|Nord Noratlas|Transall~C-160|Breguet Atlantic|Alouette~Aérospatiale Alouette|Puma~Aérospatiale Puma|Super Frelon|Écureuil~AStar~H125|EC135~H135|Agusta A109~A109|AW101~Merlin|Eurocopter Tiger~Tiger|NH90|Dornier Do X~Do X|Dornier 228|Fokker F27~Friendship|Fokker 50|Saab 340|Saab 2000|Short 360|Britten-Norman Islander~Islander|Trislander|Pilatus Porter|Grumman Albatross|Grumman Goose|Grumman Mallard|Canadair CL-415~Superscooper~CL-415|Martin Mars|Lockheed Vega~Winnie Mae|Beechcraft Bonanza~Bonanza|Diamond DA40|Extra 300|Pitts Special|Yak-52|Tiger Moth~de Havilland Tiger Moth|de Havilland Chipmunk|Stearman~Boeing Stearman|Gossamer Albatross|Gossamer Condor|Rutan Voyager|Beechcraft Starship|Piaggio P.180 Avanti~P.180 Avanti|Silver Dart~AEA Silver Dart|Stratolaunch~Roc|Enterprise~Space Shuttle Enterprise|Buran",
d:"Stipa-Caproni|Kalinin K-7|Tupolev ANT-20~Maxim Gorky|Christmas Bullet|Flying Flea~Pou-du-Ciel|Avrocar~Avro Avrocar|Custer Channel Wing|Vought V-173~Flying Pancake|XF-85 Goblin~Goblin|Goodyear Inflatoplane~Inflatoplane|Bartini Beriev VVA-14~VVA-14|Caspian Sea Monster~KM ekranoplan|Lun~Lun-class ekranoplan|Blohm & Voss BV 141~BV 141|Leduc 0.10|Coléoptère~SNECMA Coléoptère|Ryan X-13 Vertijet~Vertijet|Convair XFY Pogo~Pogo|Lockheed XFV|Short SC.1|Flying Bedstead~Rolls-Royce Thrust Measuring Rig|Fairey Rotodyne~Rotodyne|Bristol Type 188|Miles M.52|Gloster E.28/39|Coandă-1910|14-bis~Santos-Dumont 14-bis|Demoiselle~Santos-Dumont Demoiselle|Langley Aerodrome~Aerodrome|Ader Éole~Éole|Avion III|Phillips Multiplane|Edgley Optica~Optica|Mil V-12~Mi-12|Hughes XF-11|Northrop YB-49~YB-49|Burnelli UB-14|Tupolev Tu-114|Myasishchev M-50|Sukhoi T-4|Tu-95LAL|NB-36H~Crusader|Hiller Flying Platform|De Lackner HZ-1 Aerocycle~Aerocycle|Moller Skycar|Taylor Aerocar~Aerocar|ConvAirCar|Curtiss-Wright VZ-7",
k:"Caproni Ca.60~Transaereo~Noviplano|A 1921 nine-winged flying houseboat meant to carry 100 passengers across the Atlantic — it broke up on its second flight."},

{q:"Name a famous train", r:"A famous train, locomotive or named rail service (real, or famous from fiction).",
p:"Orient Express~Venice Simplon-Orient-Express~Simplon-Orient-Express|Flying Scotsman|Shinkansen~Bullet train|Eurostar|Trans-Siberian Railway~Trans-Siberian~Trans-Siberian Express|Hogwarts Express|TGV|Thomas the Tank Engine~Thomas",
c:"The General",
s:"Mallard|Rocket~Stephenson's Rocket|Polar Express~The Polar Express|Glacier Express|Bernina Express|Rocky Mountaineer|The Canadian~Canadian|The Ghan~Ghan|Indian Pacific|Blue Train~The Blue Train|Rovos Rail~Pride of Africa|Eastern & Oriental Express~Eastern and Oriental Express|Palace on Wheels|Maharajas' Express~Maharajas Express|Deccan Odyssey|Darjeeling Himalayan Railway~Darjeeling toy train~Toy Train|The Jacobite~Jacobite|Royal Scotsman|British Pullman~Belmond British Pullman|Brighton Belle|Golden Arrow|Cornish Riviera Express|Night Riviera|Caledonian Sleeper|Big Boy~Union Pacific Big Boy|20th Century Limited~Twentieth Century Limited|California Zephyr|Empire Builder|Coast Starlight|Sunset Limited|Southwest Chief|Acela~Acela Express|Silver Meteor|Pioneer Zephyr~Zephyr|City of New Orleans|Super Chief|Durango & Silverton~Durango and Silverton|Pikes Peak Cog Railway|Shanghai Maglev~Maglev|Fuxing Hao~Fuxing|Qinghai–Tibet Railway~Tibet train~Lhasa Express|KTX|ICE~InterCity Express~Intercity-Express|Frecciarossa|AVE|Thalys|Pendolino|X2000|Talgo|Sapsan|Hiawatha|Wabash Cannonball|John Bull~John Bull locomotive|Tom Thumb~Tom Thumb locomotive|DeWitt Clinton|Puffing Billy|Locomotion No. 1~Locomotion|Adler~Der Adler|City of Truro|Tornado~LNER Tornado|Duchess of Hamilton|Evening Star|Royal Train|Flying Hamburger~Fliegender Hamburger|Rheingold|Le Mistral~Mistral|Settebello|Trans Europ Express~TEE|Nord Express|Le Train Bleu~Train Bleu|Sud Express|Taurus Express|Percy~Percy the Small Engine|Gordon~Gordon the Big Engine|James~James the Red Engine|Henry~Henry the Green Engine|Edward~Edward the Blue Engine|Ivor the Engine|The Little Engine That Could|Snowpiercer|Chattanooga Choo Choo|Nozomi|Hikari|Kodama|Hayabusa|Doctor Yellow|GoldenPass Express~GoldenPass|Gornergrat Railway~Gornergrat Bahn|Jungfrau Railway~Jungfraubahn|Flåm Railway~Flamsbana~Flåmsbana|Inlandsbanan|Trans-Mongolian~Trans-Mongolian Railway|Jacobite Steam Train dup",
a:"Ferrocarril Central Andino|Hiram Bingham~Belmond Hiram Bingham|Andean Explorer|El Chepe~Chepe~Copper Canyon Railway|Tequila Express|Tren Crucero|Serra Verde Express|Corcovado Rack Railway|La Trochita~Old Patagonian Express|Train to the End of the World~Southern Fuegian Railway|Burma Railway~Death Railway|Kalka–Shimla Railway~Kalka-Shimla|Nilgiri Mountain Railway|Matheran Hill Railway|Rajdhani Express~Rajdhani|Shatabdi Express~Shatabdi|Vande Bharat Express~Vande Bharat|Samjhauta Express|Grand Trunk Express|Frontier Mail|Deccan Queen|Reunification Express|Hejaz Railway~Hijaz Railway|Baghdad Railway|Lunatic Express~Uganda Railway|Madaraka Express|TAZARA|Benguela Railway|Cape to Cairo Railway|Shongololo Express|Al Boraq|Gautrain|Spirit of Queensland|Kuranda Scenic Railway|The Overland~Overland|TranzAlpine|Northern Explorer|Coastal Pacific|Taieri Gorge Railway|Seven Stars in Kyushu|Twilight Express|Cassiopeia|Sunrise Izumo|Romancecar|Galaxy Express 999|Hello Kitty Shinkansen|Trans-Manchurian|Baikal–Amur Mainline~BAM|Red Arrow~Krasnaya Strela|Rossiya|Golden Eagle~Golden Eagle Trans-Siberian|Danube Express|Centovalli Railway|Brocken Railway~Brockenbahn|Molli|Rasender Roland|Zugspitzbahn|Pilatus Railway|Snowdon Mountain Railway|Ffestiniog Railway|Talyllyn Railway|Bluebell Railway|Severn Valley Railway|North Yorkshire Moors Railway|Isle of Man Steam Railway|Welsh Highland Railway|Romney, Hythe and Dymchurch Railway|Snaefell Mountain Railway|Volk's Electric Railway|Night Ferry|Silver Jubilee|Coronation Scot|The Elizabethan|Pines Express|Atlantic Coast Express|Master Cutler|Yorkshire Pullman|Train of Tomorrow|Aerotrain|UAC TurboTrain~TurboTrain|Metroliner|Broadway Limited|Orange Blossom Special|Phoebe Snow|Coast Daylight~Daylight|Texas Eagle|Auto Train|Circus train~Ringling Bros. circus train|Freedom Train|Royal Hudson|Holiday Train~Canadian Pacific Holiday Train|The Ocean|Polar Bear Express|Agawa Canyon Tour Train~Algoma Central|White Pass and Yukon Route~White Pass|Denali Star|Mount Washington Cog Railway|Grand Canyon Railway|Cumbres & Toltec~Cumbres and Toltec|Napa Valley Wine Train|Strasburg Rail Road|Lincoln Funeral Train",
d:"Ferrocarril Transandino~Transandine Railway|Devil's Nose~Nariz del Diablo|Madeira-Mamoré Railroad~Mad Mary|Bamboo train~Norry|Maeklong Railway~Maeklong train|Hanoi Train Street~Train Street|Ethio-Djibouti Railway|Wuppertal Schwebebahn~Schwebebahn|Train Jaune~Yellow Train|Petit train d'Artouste|La Rhune train~Chemin de fer de la Rhune|Train des Pignes|Mont Blanc Tramway|Montenvers Railway~Montenvers|Rigi Railway~Rigi Bahnen|Semmering Railway|Achenseebahn|Zillertalbahn|Rittnerbahn|Circumvesuviana|Trenino Verde|Sóller train~Tren de Sóller|Transcantábrico~El Transcantábrico|Al Ándalus|Tren de la Fresa~Strawberry Train|Comboio Presidencial~Presidential Train|Ofoten Line~Ofotbanen|Iron Ore Line~Malmbanan|Bergen Line~Bergensbanen|Train du Désert~Iron ore train|Tren Ecuador|Fairy Queen|Palace on Wheels dup|Sun Line? |Coffee Pot~Coffeepot locomotive|Stourbridge Lion|Catch Me Who Can|Best Friend of Charleston|General Haupt? |Texas~The Texas locomotive|Jupiter~Jupiter locomotive|No. 119~Union Pacific No. 119|Genf? |Invicta|Planet~Planet locomotive|Lion~Titfield Thunderbolt|Sans Pareil|Novelty~Novelty locomotive|Der Adler dup",
k:"Tren a las Nubes|Argentina's 'Train to the Clouds', climbing past 4,200 m in the Andes to cross the La Polvorilla viaduct."},

{q:"Name a type of knife", r:"A type of knife or dagger (kitchen, tool, pocket, weapon or traditional).",
p:"Swiss Army knife|Butter knife|Bread knife|Steak knife|Pocket knife~Penknife~Folding knife|Chef's knife~Chefs knife~Cook's knife|Machete|Kitchen knife",
c:"Palette knife",
s:"Butcher knife~Butcher's knife|Carving knife|Paring knife|Utility knife|Boning knife|Fillet knife~Filleting knife|Santoku|Cleaver~Meat cleaver|Nakiri|Gyuto|Petty knife|Tomato knife|Cheese knife|Oyster knife|Grapefruit knife|Mezzaluna|Ulu|Electric knife~Electric carving knife|Fish knife|Table knife~Dinner knife|Bowie knife~Bowie|Hunting knife|Survival knife|Combat knife|Bayonet|Dagger|Stiletto|Switchblade~Flick knife~Automatic knife|Butterfly knife~Balisong|Karambit~Kerambit|Kukri~Khukuri|Tantō~Tanto|Kris~Keris|Dirk|Sgian-dubh~Skean dhu|Boot knife|Push dagger|Trench knife|KA-BAR~Ka-Bar|Fairbairn–Sykes~Fairbairn-Sykes fighting knife|Throwing knife|Diving knife~Dive knife|Scalpel|Box cutter~Stanley knife|Craft knife~X-Acto knife~Hobby knife|Linoleum knife~Lino knife|Putty knife|Drywall knife~Taping knife|Hook knife|Whittling knife|Drawknife~Draw knife|Pruning knife|Grafting knife|Hori hori|Cake knife|Serrated knife|Clam knife|Letter opener|Opinel|Multi-tool~Leatherman|Laguiole|Bolo knife~Bolo|Parang|Navaja|Gravity knife|OTF knife~Out-the-front knife|Neck knife|Skinning knife|Gut hook knife|Rigging knife|Electrician's knife|Hawkbill knife|Carpet knife|Pastry knife|Channel knife|Bird's beak knife~Tourné knife|Peeling knife|Chinese cleaver~Cai dao|Scimitar? |Cutthroat razor? |Machete dup|Bread dup",
a:"Puukko|Mora knife~Mora|Leuku~Sami knife|Nessmuk|Higonokami|Kiridashi|Barong|Golok|Seax~Scramasax|Misericorde|Rondel dagger|Baselard|Cinquedea|Jambiya|Khanjar|Kirpan|Kard|Pesh-kabz|Yakutian knife~Yakut knife|Arkansas toothpick|Honesuki|Kiritsuke|Bunka|Usuba|Deba|Yanagiba|Sujihiki|Caping knife|Frozen food knife|Decorating knife|Sheepsfoot knife|Wharncliffe knife|Trapper knife|Stockman knife|Barlow knife|Congress knife|Sodbuster|Crooked knife~Mocotaugan|Main-gauche|Poniard|Katar|Bollock dagger|Ear dagger|Facón|Kaiken|Kozuka|Qama~Kindjal|Mandau|Rencong|Badik",
d:"Aikuchi|Kogatana|Bichawa|Chilanum|Pichangatti|Khanjali|Bebut|Choora|Karud|Faca de ponta~Faca|Verijero|Corvo|Yoroi-dōshi~Yoroi-doshi|Kpinga|Hunga munga|Emuckfaw? |Cuchillo? |Sica|Pugio|Parazonium|Xiphos? |Kopis|Makhaira|Falcata? |Jile? |Kaiken dup|Scian? |Scramasax dup|Sgian achlais|Bagh nakh? |Karud dup|Bhuj~Kutti|Kukri dup|Dha|Kampilan? |Kalis? |Ginunting|Pinuti? |Laring|Punal? |Dirk dup|Anelace|Cultellus|Quillon dagger|Stiletto dup|Swiss dagger~Schweizerdolch|Holbein dagger|Landsknecht dagger|Hanger? ",
k:"Tumi|A ceremonial Andean knife with a half-moon blade, used by pre-Inca and Inca cultures in sacrifices — now a national symbol of Peru."},

{q:"Name an Egyptian god or goddess", r:"A god or goddess from ancient Egyptian religion.",
p:"Ra~Re|Anubis~Anpu~Inpu|Osiris~Usir|Isis~Aset|Horus~Heru~Hor|Set~Seth~Sutekh|Bastet~Bast|Thoth~Djehuty",
c:"Pharaoh~The pharaoh",
s:"Amun~Amon~Amen|Amun-Ra~Amon-Ra~Amen-Ra|Aten~Aton|Atum|Ptah|Hathor|Sekhmet|Sobek|Khnum|Khonsu|Nut|Geb|Shu|Tefnut|Nephthys|Ma'at~Maat|Apep~Apophis|Bes|Taweret|Hapi|Khepri|Mut|Neith|Serqet~Selket|Min|Montu|Wadjet|Nekhbet|Heqet~Heket|Ammit~Ammut|Imhotep|Serapis~Sarapis|Wepwawet|Ra-Horakhty|Harpocrates|Anuket|Satet~Satis|Sopdet|Sah|Seshat|Renenutet|Nefertum|Apis~Apis bull|Meretseger|Four Sons of Horus~Sons of Horus|Imsety|Duamutef|Qebehsenuef|Nun~Nu|Ogdoad|Ennead|Aker|Babi~Baba|Heka|Hu|Sia|Shai|Meskhenet|Nehebkau|Menhit|Pakhet|Kek~Kuk|Bennu",
a:"Anhur~Onuris|Andjety|Astarte|Anat|Reshef|Qetesh~Qadesh|Bat|Iusaaset|Werethekau|Tatenen|Sokar~Seker|Khentiamentiu|Heryshaf|Banebdjedet|Mehet-Weret|Ihy|Kebechet|Nehmetawy|Shezmu|Tayet|Wosret|Raet-Tawy|Unut|Ash|Ha|Dedun|Mandulis|Arensnuphis|Apedemak|Maahes~Mahes|Buchis|Mnevis|Sopdu|Hatmehit|Naunet|Amaunet|Heh~Huh|Hauhet|Kauket|Wadj-wer|Neper|Hesat|Bata|Tutu~Tithoes",
d:"Petbe|Hedjhotep|Meret|Menqet|Nemty|Ipy|Nebethetepet|Hemen|Qebui|Sekhat-Hor|Seshmu? |Mestjet? |Wenenu? |Hededet|Mehen|Ra-Atum? |Horus the Elder~Haroeris~Horus the Great|Amenhotep son of Hapu|Ahmose-Nefertari|Montu dup|Nebtuwi? |Rattawy dup",
k:"Mafdet|The earliest known Egyptian cat goddess — older than Bastet — who guarded the pharaoh's rooms against snakes and scorpions."},

{q:"Name a pattern or print", r:"A named pattern or print — on fabric, clothes, wallpaper, tiles or knitwear.",
p:"Stripes~Striped~Stripe|Polka dots~Polka dot~Spots~Dots|Tartan~Plaid|Leopard print~Leopard|Paisley~Boteh~Buta|Houndstooth~Dogtooth~Pied-de-poule|Floral~Floral print~Flowers|Camouflage~Camo",
c:"Fingerprint",
s:"Gingham~Vichy~Vichy check|Checks~Check~Checked~Checkered~Chequered~Checkerboard|Pinstripe~Pinstripes|Herringbone|Chevron|Zigzag|Argyle|Fair Isle|Tie-dye~Tie dye|Animal print|Zebra print~Zebra|Tiger print~Tiger stripes|Snakeskin~Snake print~Python print|Cheetah print|Cow print|Giraffe print|Toile~Toile de Jouy|Damask|Chintz|Ikat|Batik|Kente|Ankara~African wax print~Dutch wax print~Wax print|Mudcloth~Bogolan|Shibori|Seigaiha|Asanoha|Aztec print|Ditsy print~Ditsy floral|Liberty print~Liberty|Harlequin|Greek key~Meander|Fleur-de-lis|Madras|Buffalo check~Buffalo plaid|Windowpane check~Windowpane|Glen check~Glen plaid~Prince of Wales check|Tattersall|Gun club check|Shepherd's check|Seersucker|Burberry check~Nova check|Monogram~Louis Vuitton monogram|Candy stripe|Breton stripe~Breton|Bengal stripe|Awning stripe|Chalk stripe|Digital camo|Dazzle camouflage~Razzle dazzle|Marble~Marbled|Terrazzo|Tortoiseshell|Honeycomb~Hexagon~Hexagons|Geometric|Op art|Moiré~Moire|Quatrefoil|Trellis|Ogee|Fish scale~Scales|Arabesque|Mandala|Suzani|Chinoiserie|Willow pattern~Blue Willow|Hawaiian print~Aloha print|Tropical print|Banana leaf~Martinique banana leaf|Ombré~Ombre|Space dye|Basketweave|Islamic geometric pattern~Girih|Celtic knot~Celtic knotwork|Tessellation|Aran~Cable knit|Intarsia|Brocade|Jacquard|Kilim|Sashiko|Pucci print~Emilio Pucci|Barocco~Versace Barocco|Unikko~Marimekko Unikko|Strawberry Thief|William Morris? |Snowflake? ",
a:"Kanga~Khanga|Kitenge|Adinkra|Adire|Aso oke|Kuba cloth|Kasuri|Katazome|Bingata|Yagasuri|Kikkō~Kikko|Shippō~Shippo|Uroko|Sayagata|Kanoko|Ichimatsu|Karakusa|Songket|Ulos|Tapa~Tapa cloth|Mola~Molas|Tenango~Otomi|Sadu|Bandhani~Bandhej|Leheriya|Phulkari|Kalamkari|Ajrakh|Block print~Block printing|Sanganeri|Bagru|Dabu|Patola|Pochampally|Kantha|Jamdani|Warli|Tatreez|Boro|Adras|Termeh|Marius pattern~Marius|Selbu rose~Selburose|Lusekofte|Bohus Stickning~Bohus|Gansey~Guernsey pattern|Black Watch~Black Watch tartan|Royal Stewart~Royal Stewart tartan|Balmoral tartan|Puppytooth|Bird's eye~Birdseye|Barleycorn|Nailhead|Sharkskin|Ticking~Ticking stripe|Regency stripe|Pyjama stripe|Butcher stripe|Hickory stripe|Bayadère~Bayadere|Penrose tiling|Conversational print~Novelty print|Paisley dup",
d:"Sanquhar pattern~Sanquhar|Setesdal~Setesdal pattern|Halland? |Delftware? |Azulejo~Azulejos|Talavera? |Zellige|Girih dup|Muqarnas? |Shoowa? |Ndop|Kitenge dup|Umblachery? |Pua Kumbu|Ulos dup|Tais|Bark cloth? |Chilkat~Chilkat weaving|Ravenstail|Coast Salish? |Pendleton? |Chimayo~Chimayó weaving|Ikat dup|Suzani dup|Kalaga|Acheik~Luntaya acheik|Pha sin? |Mudmee|Piña? |T'nalak|Inabel|Hablon? |Yakan weaving? |Kain songket dup|Sasirangan|Gringsing~Geringsing|Endek|Tapis|Tenun? |Kesi~Kesi silk|Yunjin~Yun brocade|Shu brocade|Song brocade|Nishijin-ori~Nishijin|Oshima tsumugi|Yuki tsumugi|Bashōfu~Bashofu",
k:"Shweshwe|A printed cotton from South Africa, traditionally indigo, whose crisp feel and distinctive smell come from starch added in manufacturing."},

{q:"Name something in a first-aid kit", r:"Something you'd find in (or put in) a first-aid kit.",
p:"Plaster~Plasters~Band-Aid~Band-Aids~Sticking plaster~Adhesive bandage|Bandage~Bandages|Scissors|Tweezers|Antiseptic wipes~Antiseptic~Antiseptic cream~Antiseptic wipe|Gauze~Gauze pad~Gauze pads|Gloves~Disposable gloves~Latex gloves~Nitrile gloves|Painkillers~Pain relief~Pain relievers",
c:"Instructions~First aid manual~First aid guide~Instruction leaflet~First aid booklet",
s:"Triangular bandage~Sling|Safety pins~Safety pin|Medical tape~Surgical tape~Adhesive tape~Tape|Crepe bandage~Elastic bandage~ACE bandage~Compression bandage|Cotton wool~Cotton balls|Cotton buds~Q-tips~Cotton swabs|Eyewash~Eye wash|Eye pad~Eye patch|Burn gel~Burn dressing~Burns gel|Ice pack~Cold pack~Instant cold pack|Thermometer|Space blanket~Foil blanket~Emergency blanket~Mylar blanket|CPR mask~Face shield~Resuscitation mask~Pocket mask|Hand sanitiser~Hand sanitizer|Sterile dressing~Dressing~Wound dressing|Steri-Strips~Butterfly stitches~Wound closure strips|Blister plasters~Compeed|Moleskin|Splint~SAM splint|Tourniquet|Aspirin|Paracetamol~Acetaminophen~Tylenol~Panadol|Ibuprofen~Advil~Nurofen|Antihistamines~Antihistamine~Benadryl~Allergy tablets|Hydrocortisone cream~Hydrocortisone|Calamine lotion~Calamine|Aloe vera~Aloe vera gel|Iodine~Povidone-iodine~Betadine|Hydrogen peroxide|Alcohol wipes~Alcohol swabs~Rubbing alcohol|Saline~Saline solution|Savlon|Dettol|Germolene|Neosporin|Vaseline~Petroleum jelly|Sting relief~Bite and sting cream|Tick remover~Tick tweezers|Whistle|Torch~Flashlight~Penlight|Waste bag~Clinical waste bag|Oral rehydration salts~ORS~Dioralyte~Rehydration sachets|Glucose tablets~Dextrose tablets|EpiPen~Adrenaline auto-injector~Epinephrine|Antacid~Antacids~Rennie~Tums|Imodium~Loperamide|Sunscreen~Sun cream|Finger bandage~Finger dressing|Eye drops|Tongue depressor|Syringe|Trauma shears~Tuff Cut~Bandage scissors|Roller bandage~Gauze roll|Conforming bandage|Tubular bandage~Tubigrip|Cohesive bandage~Vet wrap~Coban|Hemostatic gauze~QuikClot~Celox|Chest seal|Pressure bandage~Emergency bandage|Heat pack~Instant heat pack|Insect repellent~Bug spray|Lip balm|Cold sore cream|Magnifying glass|Notepad~Pen and paper~Pencil|Plastic bags|Inhaler",
a:"Nasopharyngeal airway~NPA|Oropharyngeal airway~Guedel airway|Pulse oximeter|Blood pressure cuff~Blood pressure monitor|Stethoscope|AED~Defibrillator|Suture kit~Sutures|Skin glue~Dermabond~Tissue adhesive|Zinc oxide tape|Kinesiology tape~KT tape|Witch hazel|Arnica~Arnica cream|Tea tree oil|Duct tape|Superglue|Finger cots|Snake bite kit|Water purification tablets|Activated charcoal|Naloxone~Narcan|Glucagon|Oral glucose gel~Glucose gel|Styptic pencil|Eye bath|Burn spray|Tincture of benzoin~Friar's Balsam|Sterile water|Emergency contact card~Emergency numbers|Medical history card? |Paper cup? |Headlamp~Head torch|Tick card|Hot water bottle? |Nail clippers|Scalpel|Splinter probe~Needle",
d:"Potassium iodide tablets~Potassium iodide~Iodine tablets|Syrup of ipecac~Ipecac|Gentian violet|Mercurochrome|Merthiolate|Asherman chest seal? |Burn sheet|Triangular dressing? |Bleeding control kit~Stop the Bleed kit|Mylar dup|Nasal tampon|Eye shield|Cervical collar~Neck brace|Rescue blanket dup|Sam dup|Hemostat~Forceps|Irrigation syringe|Magnesium sulfate? |Epsom salts|Oil of cloves~Clove oil|Benzocaine|Lidocaine cream~Lidocaine|Silver sulfadiazine|Honey dressing~Manuka honey|Hydrocolloid dressing~Hydrocolloid plasters|Tegaderm~Transparent film dressing|Melolin~Non-adherent dressing|Sofra-tulle~Tulle dressing|Crêpe dup",
k:"Israeli bandage|An emergency trauma dressing with a built-in pressure bar, invented in Israel and now carried by armies worldwide."},

{q:"Name a superstition", r:"A common superstition, lucky or unlucky belief, from anywhere in the world.",
p:"Black cat~Black cats~Black cat crossing your path|Broken mirror~Breaking a mirror~7 years bad luck~Seven years bad luck|Friday the 13th~Friday 13th|Walking under a ladder~Ladder~Walking under ladders|Knock on wood~Touch wood~Knocking on wood|Horseshoe~Lucky horseshoe|Four-leaf clover~Four leaf clover|Umbrella indoors~Opening an umbrella indoors",
c:"Bless you~Saying bless you~God bless you",
s:"Crossing your fingers~Fingers crossed~Crossed fingers|Spilling salt~Throwing salt over your shoulder~Salt over the shoulder|Lucky number 7~Lucky seven~Number 7|Unlucky 13~Number 13~Triskaidekaphobia|Unlucky number 4~Number 4~Tetraphobia|Lucky number 8~Number 8|666~Number of the beast|Rabbit's foot~Lucky rabbit's foot|Wishbone|Coin in a fountain~Throwing coins in a fountain~Wishing well|Shooting star~Wishing on a shooting star~Wishing on a star|Birthday candles~Blowing out birthday candles|Magpie~Saluting a magpie~One for sorrow|Evil eye~Nazar~Mal de ojo|Beginner's luck|Step on a crack~Cracks in the pavement|Macbeth~Saying Macbeth in a theatre~The Scottish play|Break a leg|Itchy palm~Itchy hand|Ears burning~Burning ears|Bird poo~Bird poop~Bird droppings|Lucky penny~Find a penny pick it up|Shoes on the table~New shoes on the table|Hat on the bed|Bad luck comes in threes~Comes in threes|Jinx|Dreamcatcher|Lucky charm|Seeing the bride before the wedding~Seeing the bride|Something old, something new~Something borrowed, something blue|Carrying the bride over the threshold|Rain on your wedding day|Catching the bouquet~Bouquet toss|Whistling at night~Whistling indoors|Cutting nails at night~Clipping nails at night|Chain letter|Lucky socks~Lucky underwear~Lucky shirt|Playoff beard|Curse of the Bambino|Madden curse|Sports Illustrated cover jinx|Curse of the pharaohs~Mummy's curse~Curse of Tutankhamun|Hope Diamond curse|Ravens at the Tower~Tower ravens|Itchy nose|Wrong side of the bed~Getting out of bed on the wrong side|Blowing a dandelion~Dandelion wish|Wishing on an eyelash~Eyelash|11:11|Crows~Crow|Owl hooting~Owls|Ladybird~Ladybug|Garlic~Garlic against vampires|Hamsa~Hand of Fatima|Red string~Red string bracelet|Red underwear on New Year's Eve~Red underwear|Twelve grapes~12 grapes at midnight~Doce uvas|First footing|Maneki-neko~Lucky cat~Waving cat|Feng shui|Covering mirrors~Covering mirrors after a death|Knife as a gift~Giving knives|Chopsticks upright in rice~Sticking chopsticks in rice|Writing names in red ink~Red ink|Even number of flowers|Toasting with water|Rocking an empty chair~Empty rocking chair|Upside-down shoes|Upside-down bread|Handbag on the floor~Purse on the floor|Bananas on a boat~Bananas on boats|Renaming a boat|Killing an albatross~Albatross|Setting sail on a Friday|Whistling on a ship|Tooth fairy? ",
a:"Tuesday the 13th|Friday the 17th|Haint blue|Witch bottle|Concealed shoes|Witch marks~Apotropaic marks|Rowan tree~Rowan|Bottle tree|Hex signs~Hex sign|Mojo bag~Gris-gris|Voodoo doll|Cornicello~Cornetto~Malocchio|Mano fico~Figa|Omamori|Daruma~Daruma doll|Teru teru bōzu~Teru teru bozu|Ghost month|Sweeping at night~Sweeping after dark|Washing hair on New Year's Day~Sweeping on Lunar New Year|Clock as a gift~Giving a clock|Sharing a pear|Dropped cutlery~Dropping a fork~Dropping a knife|Itchy feet|Holding your breath past a graveyard~Holding your breath past a cemetery|Seeing a hearse|Bird in the house|Bread and salt|Cats steal a baby's breath|Decorations after Twelfth Night~Christmas decorations after Twelfth Night|Dropped glove|Turning coins at the new moon~Turning money at the new moon|Rabbit rabbit~White rabbits|Crossing knives~Crossed knives|Three on a match|Peacock feathers~Peacock feathers indoors|Wearing green on stage~Green on stage|Ghost light|Whistling backstage~Whistling in a theatre|Sixpence in the Christmas pudding~Coin in the pudding|Blarney Stone~Kissing the Blarney Stone|Rubbing a statue for luck|Love locks|Groundhog Day|Pointing at a rainbow|Crickets in the house~Cricket in the house|Robin~Robin at the window|Sitting at the corner of a table|Passing the salt~Handing someone salt|Knocking three times|Stepping on a grave|Horseshoe upside down~Horseshoe the right way up|New moon wish~Wishing on a new moon",
d:"Jettatura|Paraskevidekatriaphobia~Friggatriskaidekaphobia|Hexakosioihexekontahexaphobia|Hag stone~Adder stone~Witch stone|Mandrake~Mandrake root|Hand of Glory|Born with a caul~Caul|Telling the bees|St Joseph statue~Burying a St Joseph statue|Bent sixpence|Hanging hot cross bun~Hot cross bun hanging|Corpse road|Death watch beetle~Deathwatch beetle|Pillow feathers? |Owl dup|Hen crowing~Crowing hen|Dog howling at night~Howling dog|Mirror in the bedroom? |Moles? |Pisces? |Lucky coin? |Bee? |Sneezing? |Horse brass|Knocking on the tomb? |Churchyard yew? |Unlucky green|Unlucky opal~Opals are unlucky|Pearls bring tears~Pearls at a wedding|Knife under the bed|Iron over the door|Salt on the doorstep~Salt at the threshold|Blue door? |Onion? |Tomato on the mantel? |Pennies in the shoe? |Poppy? |Hawthorn indoors~May blossom indoors",
k:"Fan death|The belief, long widespread in South Korea, that sleeping in a closed room with an electric fan running can kill you."},

{q:"Name a conspiracy theory", r:"A well-known conspiracy theory (naming it is enough — no endorsement needed).",
p:"Moon landing hoax~Fake moon landing~Moon landing was faked~Moon landing|Flat Earth~Flat earth theory~The earth is flat|Area 51~Aliens at Area 51|JFK assassination~JFK~Kennedy assassination~Second shooter|Illuminati|Chemtrails|9/11 inside job~9/11 truth~9/11|Elvis is alive~Elvis faked his death~Elvis",
c:"Birds Aren't Real~Birds are not real~Birds aren't real",
s:"Paul is dead~Paul McCartney is dead|Avril Lavigne was replaced~Avril is dead~Avril Lavigne~Melissa|Reptilians~Lizard people|Roswell~Roswell incident~Roswell UFO|Men in Black|New World Order~NWO|QAnon|Pizzagate|Denver airport~Denver International Airport|Hollow Earth|Nibiru~Planet X|Mandela effect|Titanic switch~Olympic switch theory~Titanic was the Olympic|Diana was murdered~Princess Diana~Death of Diana|Tupac is alive~Tupac|Kubrick faked the moon landing~Stanley Kubrick~Kubrick|Shakespeare didn't write his plays~Shakespeare authorship question~Oxfordian theory~Shakespeare|Bielefeld conspiracy~Bielefeld doesn't exist~Bielefeld|Finland doesn't exist~Finland conspiracy|Australia doesn't exist|Dead internet theory|5G~5G conspiracy~5G causes COVID|Vaccine microchips~Microchips in vaccines|Vaccines cause autism~Anti-vax|Fluoride~Water fluoridation~Fluoride in the water|HAARP|Philadelphia Experiment|Montauk Project|MKUltra~MK-Ultra|Majestic 12~MJ-12|Project Blue Beam~Blue Beam|Face on Mars|Ancient aliens~Ancient astronauts~Aliens built the pyramids|Black helicopters|FEMA camps|Jade Helm|Birtherism~Birther~Obama birth certificate|Deep state|Epstein didn't kill himself~Epstein|Kurt Cobain was murdered~Kurt Cobain~Cobain|Walt Disney's frozen head~Walt Disney frozen~Walt Disney|Weather control~Weather manipulation|Hollow Moon|Tartaria~Mud flood|Georgia Guidestones|Bohemian Grove|Skull and Bones|Freemasons~Masons|Knights Templar|Priory of Sion|Bilderberg Group~Bilderberg|Trilateral Commission|Agenda 21|Great Reset|15-minute cities|Hitler escaped to Argentina~Hitler survived~Hitler is alive|Nazi moon base~Nazi UFOs~Die Glocke|Ice wall~Antarctic ice wall|Anastasia survived~Anastasia|Stevie Wonder isn't blind~Stevie Wonder can see|Cure for cancer is hidden~Big Pharma~Hidden cancer cure|Chemtrail dup",
a:"Dulce Base|Hangar 18~Wright-Patterson Hangar 18|Project Serpo|Black Knight satellite|Secret space program|Wyoming doesn't exist|Star forts|Agartha|Shaver Mystery|Kecksburg UFO~Kecksburg|Rendlesham Forest incident~Rendlesham|Phoenix Lights|Maury Island incident|Dyatlov Pass incident~Dyatlov Pass|Tesla's death ray~Tesla's lost inventions~Tesla|Free energy suppression~Free energy|Water-powered car~Stanley Meyer|Fish carburetor~100 mpg carburetor|Smart meters|MLK assassination~Martin Luther King assassination|Pearl Harbor advance-knowledge~Pearl Harbor|Club of Rome|Operation Highjump|Bermuda Triangle|Cattle mutilations~Cattle mutilation|Magic bullet~Magic bullet theory|Grassy knoll|Umbrella Man|Badge Man|Babushka Lady|Three tramps|Dag Hammarskjöld crash~Hammarskjöld|Olof Palme assassination~Palme|Jim Morrison is alive|Apollo 20|Van Allen belts~Van Allen radiation|Moon is a hologram|Firmament|Contrails dup|Havana syndrome? ",
d:"Baconian theory~Francis Bacon wrote Shakespeare|Marlovian theory~Marlowe wrote Shakespeare|New Chronology~Fomenko|Mars Anomaly? |Dogon Sirius mystery~Sirius Mystery|Nazca aliens~Nazca Lines aliens|Piri Reis map|Baghdad Battery|Antikythera aliens? |Vimana~Vimanas|Stargate Project? |Shag Harbour UFO~Shag Harbour|Westall UFO~Westall|Ariel School UFO~Ariel School|Flatwoods monster|Hopkinsville goblins~Kelly–Hopkinsville encounter|Men in Black dup|Silence Group|Mothman Prophecies? |Point Pleasant? |Paul Bearer? |Stonehenge UFO? |Operation Paperclip? |Nazi bell dup|Vril Society~Vril|Thule Society|Hollow Earth dup|Symmes Hole~Symmes|Koreshanity~Cyrus Teed|Hohlweltlehre? |Phantom Island? |Sandy Hook? ",
k:"Phantom time hypothesis~Phantom time|The claim that nearly 300 years of the early Middle Ages (614–911 AD) never happened and were invented by medieval rulers."},

{q:"Name a water sport", r:"A sport or activity done in, on or under water.",
p:"Swimming|Surfing|Water polo|Diving|Kayaking|Rowing|Water skiing~Waterskiing~Water-skiing|Sailing",
c:"Fishing~Angling~Sport fishing",
s:"Canoeing|Rafting~White-water rafting~Whitewater rafting|Windsurfing~Boardsailing|Kitesurfing~Kiteboarding~Kite surfing|Wakeboarding|Jet skiing~Jet ski~Jetskiing|Paddleboarding~SUP~Stand-up paddleboarding~Stand up paddle~Paddle boarding|Bodyboarding~Boogie boarding|Snorkelling~Snorkeling|Scuba diving~Scuba|Freediving~Free diving|Cliff diving|Artistic swimming~Synchronised swimming~Synchronized swimming|Open water swimming~Marathon swimming~Wild swimming|Triathlon|Dragon boat racing~Dragon boating~Dragon boat|Canoe slalom|Canoe sprint|Powerboat racing~Powerboating|Yachting|Parasailing|Kneeboarding|Skimboarding|Wakesurfing|Tubing|Banana boat|Flyboarding~Flyboard|Underwater hockey~Octopush|Canoe polo~Kayak polo|Surf lifesaving~Lifesaving|Coasteering|Canyoning|Riverboarding~River boarding~Hydrospeed|Foiling~Hydrofoiling~Foil surfing~eFoil|Wing foiling~Wingfoil~Wingsurfing|Sea kayaking|Outrigger canoeing~Outrigger~Va'a|Aqua aerobics~Water aerobics|Aquathlon|Swimrun|Spearfishing|Barefoot skiing~Barefoot waterskiing|Cable wakeboarding~Cable skiing|Big wave surfing|Tow-in surfing|Sculling|Punting|High diving|Platform diving|Springboard diving|Water basketball|Water volleyball|Marco Polo|Ice swimming~Winter swimming|Polar plunge~Polar bear plunge|Channel swimming~English Channel swim|Hydroplane racing|Jetboat racing~Jet sprint|Whitewater kayaking~Freestyle kayaking|Packrafting|Fly fishing|Surfski~Surf ski|SUP yoga~Paddleboard yoga|Mermaiding|Finswimming|Dinghy sailing|Catamaran sailing~Catamaran|America's Cup|Ocean Race~Volvo Ocean Race|Vendée Globe~Vendee Globe|Sydney to Hobart~Sydney to Hobart Yacht Race|The Boat Race~Boat Race~Oxford–Cambridge Boat Race|Henley~Henley Royal Regatta|Regatta|Pilot gig racing~Gig racing|Coastal rowing|Canoe marathon|Wildwater canoeing|Water polo dup",
a:"Underwater football|Underwater orienteering|Underwater target shooting|Bog snorkelling~Bog snorkeling|Bathtub racing|Swimming with sharks? |Cage diving~Shark cage diving|Cave diving|Wreck diving|Ice diving|Night diving|Drift diving|Apnea~Static apnea|Spearfishing dup|Noodling|Big-game fishing~Game fishing|Bass fishing|Ice fishing|Deep-sea fishing|Sport kayaking? |Kayak surfing|Wave ski|Prone paddleboarding~Prone paddling|Surf boat rowing~Surf boats|Beach flags? |Rescue tube? |Ski racing (water)? |Show skiing~Water ski show|Trick skiing|Slalom skiing|Ski jumping (water)~Water ski jumping|Hydrofoil racing? |Offshore powerboat racing~Offshore racing|Formula 1 Powerboat~F1H2O|UIM? |Match racing|Fleet racing? |Ice yachting? |Land yachting? |Rafting dup|Zorbing? |Aquabike~Jet ski racing|Water walking? |Water rugby|Water pole? |Fin swimming dup|Mermaid swimming? |Lifeguard racing? ",
d:"Kayak jousting? |Water jousting~Joute nautique~Boat jousting|Fischerstechen|Gondola racing~Regata Storica|Palio del Golfo? |Snake boat race~Vallam Kali~Nehru Trophy Boat Race|Chuan long? |Naadam? |Coracle racing~Coracle|Bathtub dup|Totnes Orange Race? |Cardboard boat race~Cardboard boat regatta|Pumpkin regatta~Giant pumpkin regatta|Henley-on-Todd Regatta~Henley on Todd|Rubber duck race? |Pooh sticks? |Swamp soccer? |Mud racing? |Wife carrying? |Hydrospeed dup|Tube racing? |Stone skipping~Skimming stones|Canal jumping~Fierljeppen|Walking on water? |Gig dup|Lagoon diving? |Aquajogging~Deep water running|Water tag? |Pearl diving|Ama diving~Ama|Haenyeo diving~Haenyeo",
k:"Underwater rugby|Played three to five metres down in a deep pool with a saltwater-filled ball that sinks — the goals are metal baskets on the bottom."},

{q:"Name a playground game", r:"A game children play in the playground, school yard or street (any country).",
p:"Tag~Tig~It~Tip~Tiggy~Chase~Tag you're it|Hide and seek~Hide-and-seek|Hopscotch~Rayuela|Skipping~Jump rope~Skipping rope|Red Rover|Duck, duck, goose~Duck duck goose|Simon says|Marbles",
c:"Rock paper scissors~Rock, paper, scissors~Roshambo~Paper scissors stone~Scissors paper stone",
s:"What's the time, Mr Wolf?~What's the time Mr Wolf|Red light, green light~Red Light Green Light|Kiss chase|The floor is lava~Floor is lava~Hot lava|Four square~4 square|Tetherball|Dodgeball|Kickball|Hot potato|Stuck in the mud|British bulldog~Bulldog|Cops and robbers~Chor police|Clapping games~Hand clapping games~Pat-a-cake|Cat's cradle|Conkers|Jacks~Knucklebones|Elastics~Chinese jump rope~Gummitwist|Double Dutch|Chinese whispers~Telephone~Broken telephone|Grandmother's footsteps~Statues|Sleeping lions|Fox and hounds|Capture the flag|Leapfrog|Tug of war|Ring a ring o' roses~Ring around the rosie|Oranges and lemons|London Bridge~London Bridge is falling down|The farmer's in his den~Farmer in the dell|Hokey cokey~Hokey pokey|Mother may I?~Mother May I|Follow the leader|Freeze tag|Sardines|Kick the can|Gaga ball~Gaga|Wall ball~Butts up|Handball~Downball|Spud|Chain tag~Chain tig|Sharks and minnows~Octopus|Crack the whip|Ringolevio~Relievo|I spy|Thumb war~Thumb wrestling|Slaps~Red hands|Cootie catcher~Fortune teller~Chatterbox|Pogs|Yo-yo~Yoyo|Hula hoop|Spinning top~Tops|Hacky sack~Footbag|Heads up, seven up~Heads Up Seven Up~Heads down thumbs up|Monkey in the middle~Piggy in the middle~Keep away|Blind man's buff~Blind man's bluff|Marco Polo|Musical statues|Wink murder|Ghost in the graveyard|Stoop ball~Stoopball|Stickball|Skully~Skelly|Johnny on the pony~Johnny-on-a-pony|Queenie~Queenie-i-o|Tunnel tag|Off-ground tag~Off ground touch|Zombie tag|Shadow tag|Manhunt|Traffic lights|Kerby|Rounders|Three-legged race|Sack race|Egg and spoon race|Wheelbarrow race|Chicken fight~Piggyback fight|Truth or dare|Hangman|Pooh sticks|Musical chairs|Grounders|Dodgeball dup|Kendama|Menko|Daruma-san ga koronda~Daruma san ga koronda|Kagome kagome|Hana ichi monme|Ddakji|Gonggi|Mugunghwa kkoch-i pieot seumnida~Mugunghwa|Jegichagi|Jianzi~Shuttlecock kicking~Chapteh|Gilli-danda~Gilli danda|Lagori~Pittu~Seven stones|Langdi|Ice and water~Ice water|Kabaddi|Sepak raga? ",
a:"Mumblety-peg~Mumbletypeg|Split the kipper|Ampe|Oonch neech|Vish amrit|Kancha|Kith-kith~Stapu|Chhupan chhupai|Pallanguzhi? |Aadu puli? |Pittu dup|Pañuelo~Capture the handkerchief|Elástico? |Sete pedrinhas? |Pique-esconde? |Queimada~Queimado|Amarelinha|Pião? |Pilla-pilla|Escondite~Escondidas|Rayuela dup|Balón prisionero|Jeu de l'oie? |Loup~Le loup|1, 2, 3, soleil~Un, deux, trois, soleil|Épervier? |Chat perché|Gummitwist dup|Fangen? |Himmel und Hölle|Plumpsack|Ochs am Berg|Kastanjes? |Tikkertje|Verstoppertje? |Annemaria koekoek|Zakdoekje leggen|Cache-cache? |Nascondino|Un, due, tre, stella|Campana~Settimana|Palla prigioniera|Strega comanda colore|Ce-o-leapsa? |Salki? |Klassiki|Kazaki-razboyniki~Cossacks and robbers|Lapta|Gorodki|Chizhik|Zhmurki|Cat and mouse~Cat and Mouse|Bull in the ring? |Poison ball|Kerby dup|Tag rugby? |Chinese checkers? |Squirrel in the tree? |Duck duck grey duck|Red rover dup|Bullrush~Bull rush|Poison? |Bin ball? |Stingers? |Suicide? |Seven up~Sevens|Ghosts? |Cooties|Tip the can? |Hide and go seek dup",
d:"Pilolo|Nhodo|Tsoro? |Diketo|Kgati|Morabaraba? |Ncuva? |Kudoda|Ampe dup|Da ga? |Tumba? |Kukla? |Sepak dup|Congkak? |Galah panjang|Tuho? |Yut? |Biểu? |Ô ăn quan? |Tatsu? |Takeuma~Bamboo stilts|Ohajiki|Oni gokko~Onigokko|Kakurenbo|Ishikeri|Pachisi? |Luksong tinik|Patintero|Tumbang preso|Sipa|Piko|Agawan base|Langit lupa|Chinese garter|Sungka? |Tinikling? |Kho kho dup",
k:"Kho kho|An Indian tag game where the chasers crouch in a line facing alternate ways and can only swap in by tapping a teammate's back and shouting 'kho'."},

{q:"Name a saint", r:"A saint (canonised, traditional, or venerated in any Christian church).",
p:saints("Patrick|Nicholas~Nicolas|Peter|Paul|Francis of Assisi~Francis|George|Valentine|!Mother Teresa~Saint Teresa of Calcutta~St Teresa of Calcutta~Teresa of Calcutta"),
c:saints("Bernard of Menthon~Bernard"),
s:saints("Andrew|David|Christopher|Joan of Arc~Joan|Anthony of Padua~Anthony|Jude|Matthew|Mark|Luke|John~John the Evangelist|John the Baptist|James~James the Great|Thomas~Doubting Thomas|Stephen|!Virgin Mary~Mary~Saint Mary~St Mary~The Virgin Mary~Blessed Virgin Mary~Our Lady|Joseph|Mary Magdalene|Augustine~Augustine of Hippo|Thomas Aquinas~Aquinas|Benedict|Dominic|Ignatius of Loyola~Ignatius|Francis Xavier|Teresa of Ávila~Teresa of Avila|Thérèse of Lisieux~Therese of Lisieux~Thérèse|Catherine of Siena|Clare~Clare of Assisi|Bernadette~Bernadette of Lourdes|Lucy~Lucia|Agnes|Cecilia|Barbara|Catherine of Alexandria~Catherine|Margaret|Anne|Elizabeth|Helena|Monica|Brigid~Bridget~Brigid of Kildare|Columba~Colmcille|Aidan|Cuthbert|Bede~Venerable Bede|Alban|Edmund|Edward the Confessor|Thomas Becket~Becket|Thomas More|Swithin|Dunstan|Hilda~Hilda of Whitby|Mungo~Kentigern|Ninian|Margaret of Scotland|Kevin|Brendan~Brendan the Navigator|Columbanus|Boniface|Ansgar|Olaf|Eric~Erik|Bridget of Sweden~Birgitta|Wenceslas~Wenceslaus|Stanislaus|Casimir|Hedwig|Cyril|Methodius|Vladimir|Olga|Basil~Basil the Great|Gregory~Gregory the Great|John Chrysostom|Athanasius|Jerome|Ambrose|Anthony the Great~Anthony of Egypt|Simeon Stylites|Denis~Denys|Martin~Martin of Tours|Genevieve|Louis~Louis IX|Rose of Lima|Martin de Porres|Juan Diego|Kateri Tekakwitha|Elizabeth Ann Seton|Frances Cabrini~Mother Cabrini|John Paul II~Pope John Paul II|John XXIII~Pope John XXIII|!Padre Pio~Saint Pio~St Pio~Pio of Pietrelcina|Faustina|Maximilian Kolbe~Kolbe|Óscar Romero~Oscar Romero|Philip Neri|Vincent de Paul|Francis de Sales|John of the Cross|Rita~Rita of Cascia|Sebastian|Blaise|Roch~Rocco|Florian|Hubert|Crispin|Lawrence~Laurence|Leonard|Giles|Vitus|Erasmus~Elmo|Michael~Michael the Archangel|Gabriel|Raphael|Apollonia|Agatha|Ursula|Veronica|Scholastica|Walpurga|Odile|Gertrude|Hildegard of Bingen~Hildegard|Bruno|Norbert|Bernard of Clairvaux|Anselm|Bonaventure|Albert the Great~Albertus Magnus|Isidore~Isidore of Seville|Philip|Bartholomew|Simon|Matthias|Barnabas|Timothy|Titus|Junípero Serra~Junipero Serra|Damien~Father Damien~Damien of Molokai|Katharine Drexel|Josephine Bakhita~Bakhita|Charles Lwanga|Andrew Kim Taegon|Lorenzo Ruiz|Paul Miki|Alphonsa|John Henry Newman~Newman|Edith Stein~Teresa Benedicta of the Cross|Carlo Acutis|Dominic Savio|John Bosco~Don Bosco|Maria Goretti|Jean Vianney~John Vianney|Joseph of Arimathea|Longinus|Dismas~The Good Thief|Lazarus|Martha|Joachim|Piran|Winifred|Chad|Wilfrid|Oswald|Etheldreda~Audrey|Frideswide|Augustine of Canterbury|Nino~Nina|Gregory the Illuminator|Expeditus|Joseph of Cupertino"),
a:saints("Isidore the Farmer|James the Less|Mary of Egypt|Mesrop Mashtots|Frumentius|Isaac Jogues|Marianne Cope|Kizito|Pedro Calungsod|Gianna Beretta Molla|Gemma Galgani|Catherine Labouré|Louis de Montfort|Margaret Mary Alacoque|Nicodemus|Zechariah|Charles Borromeo|Josemaría Escrivá~Josemaria Escriva|Petroc|Teilo|Illtud|Beuno|Dyfrig~Dubricius|Cedd|Werburgh|Guthlac|Botolph|Birinus|Paulinus|Asaph|Kenelm|Magnus~Magnus of Orkney|Sunniva|Hallvard|Kilian|Gall|Fridolin|Meinrad|Nicholas of Flüe~Brother Klaus|Wiborada|Afra|Ulrich|Corbinian|Emmeram|Rupert|Pirmin|Leodegar~Leger|Radegund|Clotilde|Remigius~Remi|Eligius~Eloi|Wandrille|Gummarus|Rumbold|Dymphna|Amalberga|Bavo|Lambert|Servatius|Gudula|Samson of Dol|Malo|Tugdual|Corentin|Ronan|Hervé~Herve|Yves~Ivo of Kermartin|Winwaloe~Guénolé|Kieran~Ciarán|Finbarr|Fursey|Gobnait|Ita|Declan|Enda|Canice~Kenny|Malachy|Oliver Plunkett|Laurence O'Toole|Fiacre|Drogo|Médard|Thorlak|Henrik~Henry of Uppsala|Botvid|Sergius of Radonezh|Seraphim of Sarov|Xenia of Saint Petersburg~Xenia|Tikhon|Alexander Nevsky|Boris and Gleb~Boris~Gleb|Nectarios~Nektarios|Spyridon|Demetrius~Demetrios|Paraskevi|Nino dup"),
d:saints("Wilgefortis~Uncumber|Simeon the Holy Fool|Christina the Astonishing|Cuthman|Wite~Candida|Sidwell~Sativola|Melangell|Dwynwen|Non~Nonna|Ia~Ia of Cornwall|Kea|Endelienta|Nectan|Morwenna|Brannoc|Urith|Juthwara|Walstan|Osyth|Edburga|Eanswythe|Milburga|Mildred|Tibba|Rumwold|Alkelda|Rognvald|Brioc|Kevin dup|Kenelm dup|Ebba|Bega~Bee|Cybi|Seiriol|Tysilio|Pedrog? |Cadoc|Gwynllyw~Woolos|Tathan|Govan|Justinian~Stinan|Caradog? |Keyne|Neot|Germoe|Just~Justus|Mawes|Ives~Ia dup|Senara|Buryan|Levan|Mewan|Austell|Clether|Budoc|Winnow? |Gluvias|Gennys|Keverne"),
k:"Saint Guinefort~St Guinefort~Guinefort|A greyhound venerated as a folk saint in medieval France after saving a baby from a snake — the Church never recognised him."},

{q:"Name a hotel chain", r:"A hotel chain or hotel brand (anywhere in the world).",
p:"Hilton|Marriott|Holiday Inn|Premier Inn|Best Western|Ritz-Carlton~Ritz~The Ritz|Four Seasons|Hyatt",
s:"Sheraton|Westin|W Hotels~W Hotel|St. Regis~St Regis|Le Méridien~Le Meridien|Renaissance Hotels~Renaissance|Courtyard~Courtyard by Marriott|Fairfield Inn~Fairfield|Residence Inn|SpringHill Suites|Moxy|Aloft|JW Marriott|Waldorf Astoria~Waldorf-Astoria|Conrad|DoubleTree~DoubleTree by Hilton|Hampton Inn~Hampton by Hilton~Hampton|Embassy Suites|Homewood Suites|Hilton Garden Inn|Park Hyatt|Grand Hyatt|Hyatt Regency|Andaz|Hyatt Place|InterContinental~Intercontinental|Crowne Plaza|Holiday Inn Express|Kimpton|Hotel Indigo~Indigo|Six Senses|Regent~Regent Hotels|Staybridge Suites|Candlewood Suites|Accor|Novotel|Ibis~Ibis Budget~Etap|Mercure|Sofitel|Pullman|Fairmont|Raffles|Swissôtel~Swissotel|Mövenpick~Movenpick|Mama Shelter|25hours~25hours Hotels|Radisson~Radisson Blu|Park Plaza|Wyndham|Ramada|Days Inn|Super 8|Travelodge|La Quinta|Howard Johnson~HoJo|Motel 6|Red Roof Inn~Red Roof|Choice Hotels|Comfort Inn|Quality Inn|Econo Lodge|Sleep Inn|Clarion|Tryp~TRYP|Mandarin Oriental|The Peninsula~Peninsula|Shangri-La|Aman~Aman Resorts|Rosewood|The Oberoi~Oberoi|Taj~Taj Hotels|The Leela~Leela|Banyan Tree|Anantara|Dusit Thani~Dusit|Jumeirah|Rotana|Kempinski|Steigenberger|Maritim|Motel One|Meininger|Scandic|Strawberry~Nordic Choice|NH Hotels~NH|Meliá~Melia|Iberostar|Barceló~Barcelo|Riu~RIU|Pestana|Malmaison|Hotel du Vin|De Vere|Club Med|Sandals|Hard Rock Hotel~Hard Rock|Great Wolf Lodge|Loews~Loews Hotels|Omni~Omni Hotels|Ace Hotel|The Standard~Standard|Edition~EDITION|citizenM~Citizen M|Generator~Generator Hostels|Hostelling International~HI Hostels~YHA|Selina|Yotel~YOTEL|The Hoxton~Hoxton|Soho House|APA Hotel~APA|Toyoko Inn|Dormy Inn|Hoshino Resorts~Hoshinoya|Hotel Okura~Okura|Hotel Nikko~Nikko|Lotte Hotel~Lotte|The Shilla~Shilla|Jin Jiang|OYO~OYO Rooms|Pan Pacific|Parkroyal|Protea Hotels~Protea|Belmond~Orient-Express Hotels|Extended Stay America|Sonesta|Graduate Hotels~Graduate|Virgin Hotels|Nobu Hotels~Nobu Hotel|Bulgari Hotels~Bulgari Hotel",
a:"Pousadas de Portugal~Pousadas|Relais & Châteaux~Relais et Chateaux|Romantik Hotels|Van der Valk|Golden Tulip|Campanile|Kyriad|Première Classe~Premiere Classe|B&B Hotels|Formule 1~hotelF1~F1 hotel|Logis~Logis Hotels|Leonardo Hotels|Dan Hotels|Soneva|COMO Hotels~COMO|Rocco Forte Hotels~Rocco Forte|Dorchester Collection|Oetker Collection|Lemon Tree Hotels~Lemon Tree|Ginger Hotels~Ginger|Nine Hours~9h nine hours|Maldron Hotels~Maldron|Clayton Hotels|Jurys Inn|Village Hotels~Village Hotel|Macdonald Hotels|Hampton by Hilton dup|Curio Collection~Curio|Canopy by Hilton~Canopy|Tru by Hilton~Tru|Home2 Suites|Autograph Collection|Element~Element Hotels|Tribute Portfolio|Luxury Collection~The Luxury Collection|Hyatt House|Thompson Hotels|Alila|voco|Even Hotels|Adagio|MGallery|Novotel dup|Park Inn|art'otel|Cambria Hotels~Cambria|Ascend Collection|Rodeway Inn|Microtel|Baymont|Wingate|Hawthorn Suites|Dolce Hotels|H10 Hotels~H10|Small Luxury Hotels~SLH|Leading Hotels of the World|Design Hotels|Tsogo Sun|Sun International|City Lodge|Southern Sun|Serena Hotels~Serena|Rydges|Quest Apartment Hotels~Quest|Mantra|Oaks Hotels~Oaks|Peppers|QT Hotels~QT|Centara|Amari|Avani|ITC Hotels~ITC|Sarovar|Huazhu|Hanting|Home Inn|Atour|GreenTree|Prince Hotels|Tokyu Stay|Richmond Hotels|Super Hotel|Route Inn~Hotel Route Inn|Mitsui Garden Hotels~Mitsui Garden|Zoku|Landal GreenParks~Landal|Center Parcs|Butlin's~Butlins|Fletcher Hotels|Bastion Hotels|Thon Hotels~Thon|Arcotel|Austria Trend Hotels|Isrotel|Fattal|Capella Hotels~Capella|Cheval Blanc|Armani Hotel~Armani|Baccarat Hotel|Sofitel Legend|Faena|Edition dup|Viceroy|Montage~Montage Hotels|Auberge Resorts~Auberge|One&Only~One and Only",
d:"Studio 6|WoodSpring Suites|Knights Inn|Americas Best Value Inn|Scottish Inns|Red Carpet Inn|Magnuson Hotels|Drury Hotels~Drury Inn|Cobblestone Hotels|Stoney Creek Hotels|Kasa|Sonder|Mint House|Citadines|Ascott|Oakwood|Fraser Suites~Frasers|Somerset|Lyf|Tune Hotels|Red Planet Hotels~Red Planet|Zostel|Treebo|FabHotels|Sterling Holidays|Club Mahindra|Vivanta|SeleQtions|Ginger dup|Hoshinoya dup|First Cabin|Book and Bed Tokyo|Sotetsu Fresa Inn|Hotel Gracery~Gracery|Keio Presso Inn|Daiwa Roynet|Tokyu Rei|Via Inn|Comfort Hotel? |Karlsson? |Sokos Hotels~Sokos|Cumulus|Omena Hotels~Omena|Arthotel ANA? |Moxy dup|prizeotel|Ruby Hotels~Ruby|Adina|Lindner Hotels~Lindner|Dorint|Seaside Hotels? |A&O Hostels~a&o|Wombat's~Wombats|St Christopher's Inns~St Christopher's|Hoxton dup|Hilton Tapestry~Tapestry Collection|Motto by Hilton~Motto|Spark by Hilton~Spark|Signia by Hilton~Signia|LXR Hotels~LXR|Caption by Hyatt~Caption|Hyatt Centric~Centric|Hyatt Ziva~Ziva|Hyatt Zilara~Zilara|Dreams Resorts~Dreams|Secrets Resorts~Secrets|Breathless Resorts|Excellence Resorts~Excellence|Couples Resorts~Couples|Beaches Resorts~Beaches|Karisma? |Palace Resorts|Grand Velas~Velas|Paradisus|Occidental Hotels~Occidental|Catalonia Hotels~Catalonia|Eurostars|Vincci|Hotusa? |Sercotel|Room Mate Hotels~Room Mate|Petit Palace|Pestana Pousadas? |Vila Galé~Vila Gale|Tivoli Hotels~Tivoli|Minor Hotels",
k:"Paradores~Parador~Paradores de Turismo|Spain's state-run hotel chain, set in castles, convents and palaces — the first opened in 1928."}
]);
